openai:
  "api_key": "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"
  "model": "gpt-3.5-turbo"
  "temperature": 1.0
  "max_tokens": 100
  "time_sleep": 30

data:
  "nrows": 10

paths:
  "raw_data": "./data"
  "descriptions": "./descriptions"

messages:
  "descriptions": "Напиши описание следующего столбца данных"
  "similar_columns": "Выбери для следующего текста наиболее подходящий ключ из словаря по его схожести со значением по этому ключу"